---
title: "QUALIMAP Comparison Report"
output: pdf_document
params:
  folder_name: NA
  bases_comparison: NA
  contig_comparison: NA
  reads_comparison: NA
  mapped_paired_reads_comparison: NA
  mapped_paired_reads_singletons_comparison: NA
  mapped_bases_comparison: NA
  duplicated_reads_comparison: NA
  mapping_quality_comparison: NA
  insert_size_mean_comparison: NA
  coverage_mean_comparison: NA
  gc_percentage_comparison: NA
  actg_content_comparison: NA
---

## File
- **Folder: ** `r params$folder_name`


## Reference
```{r echo=FALSE, out.width="70%"}
print(params$bases_comparison)
```


```{r echo=FALSE, out.width="70%"}
print(params$contig_comparison)
```


## Read Statistics
```{r echo=FALSE, fig.width=10, fig.height=5}
print(params$reads_comparison)
```


```{r echo=FALSE, out.width="80%"}
print(params$mapped_paired_reads_comparison)
```


```{r echo=FALSE, out.width="80%"}
print(params$mapped_paired_reads_singletons_comparison)
```


```{r echo=FALSE, fig.width=10, fig.height=5}
print(params$mapped_bases_comparison)
```


### Duplication Rate Histogram:
```{r echo=FALSE, out.width="80%"}
print(params$duplicated_reads_comparison)
```


### Mapping Quality Histogram:
```{r echo=FALSE, out.width="80%"}
print(params$mapping_quality_comparison)
```


## Insert Size
```{r echo=FALSE, out.width="80%"}
print(params$insert_size_mean_comparison)
```

## Data Coverage
```{r echo=FALSE, out.width="80%"}
print(params$coverage_mean_comparison)
```

## ACTG Content
```{r echo=FALSE, out.width="80%"}
print(params$actg_content_comparison)
```


### CG content distribution:
```{r echo=FALSE, out.width="80%"}
print(params$gc_percentage_comparison)
```
